apiVersion: apps/v1
kind: Deployment
metadata:
  name: onedev
spec:
  template:
    spec:
      containers:
      - name: onedev
        resources:
          requests: 
            cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql 
spec:
  template:
    spec:
      containers:
      - name: mysql
        resources:
          requests: 
            cpu: 500m
