apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: onedev
subjects:
- kind: ServiceAccount
  name: onedev
roleRef:
  kind: ClusterRole
  name: onedev
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onedev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: onedev
subjects:
- kind: ServiceAccount
  name: onedev
