apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: onedev
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: onedev
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "secrets", "events"]
  verbs: ["create", "get", "list", "watch", "delete"]
