apiVersion: apps/v1
kind: Deployment
metadata:
  name: onedev
spec:
  template:
    spec:
      containers:
      - name: onedev
        resources:
          requests: 
            memory: 1Gi
          limits:
            memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql 
spec:
  template:
    spec:
      containers:
      - name: mysql
        resources:
          requests: 
            memory: 512Mi
          limits:
            memory: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onedev
spec:
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
spec:
  resources:
    requests:
      storage: 1Gi
